/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/treeLP3.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Tree(props) {
  const { nodes, materials } = useGLTF('./models/treeLP3.glb')
  return (
    <group {...props} dispose={null} scale={3}>
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.001']} position={[0.07, 0.44, -0.02]} scale={0.41} />
      <mesh geometry={nodes.Sphere002.geometry} material={materials['Material.002']} position={[0.07, 4.2, -0.02]} scale={[2.13, 2.16, 2.13]} />
    </group>
  )
}

useGLTF.preload('./models/treeLP3.glb')
